language: java
jdk:
- oraclejdk7
- openjdk7
notifications:
  email: false
deploy:
  provider: s3
  access_key_id: AKIAIEAZWUZAFXQDCGNQ
  secret_access_key:
    secure: LyO9om5NYqf/TC9wSuv767wJiPSwi6PCB+pbYo1S9nTgrXg6V8XgbYropoLIEisrZLOhEZFGuQq3Zo6TdAPuFS6gVguYzEqbhnW/KuD9qcnNjt4Q7S6EOgCwXBlKQochXPivrogw3fpItw1ygrGgXY40nn5ttURNZ5EjR64ytjE=
  bucket: craftcontrol
  on:
    repo: madjam002/CraftControl
