name: CraftControl
main: com.madjam002.craftcontrol.CraftControl
version: 0.0.2

permissions:
    craftcontrol.craft.*:
        description: Allows the player to craft certain items
        default: true
    craftcontrol.smelt.*:
        description: Allows the player to smelt certain items
        default: true